import { type NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
	const allWords = trpc.dictionary.getAll.useQuery();

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="f-full container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
				<div className="overflow-x-auto">
					<table className="table w-full">
						<thead>
							<tr>
								<th></th>
								<th>Word</th>
								<th>Translation</th>
								<th>Created at</th>
							</tr>
						</thead>
						<tbody>
							{allWords.data?.map((entry, index) => (
								<tr key={entry.id}>
									<th>{index}</th>
									<td>{entry.word}</td>
									<td>{entry.translation}</td>
									<td>{entry.createdAt.toDateString()}</td>
								</tr>
							))}
						</tbody>
					</table>
				</div>
			</main>
		</>
	);
};

export default Home;
