import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useCallback } from "react";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
	const router = useRouter();
	const allDocuments = trpc.document.getAll.useQuery();

	const loadDocumentFromId = useCallback(
		(id: string) => {
			router.push(`/editor/${id}`);
		},
		[router]
	);

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="container mx-auto flex h-full flex-col items-center justify-center p-4">
				<div className="min-w-full overflow-x-auto">
					<table className="table w-full">
						<thead>
							<tr>
								<th></th>
								<th>Title</th>
								<th className="w-1/6">Created at</th>
							</tr>
						</thead>
						<tbody>
							{allDocuments.data?.map((entry, index) => (
								<tr key={entry.id}>
									<th>{index}</th>
									<td onClick={() => loadDocumentFromId(entry.id)}>
										{entry.title}
									</td>
									<td>{entry.createdAt.toDateString()}</td>
								</tr>
							))}
						</tbody>
					</table>
				</div>
			</main>
		</>
	);
};

export default Home;
